UPDATE tasks SET status_workloads = (
    CASE
        WHEN status = 'PENDING' THEN
            '{"PENDING":' || COALESCE(workload, 0) || ',"ASSIGNED":0,"RECEIVED":0,"IN_PROGRESS":0,"SUBMITTED_FOR_QA":0,"QA_COMPLETING":0,"QA_COMPLETED":0}'
        WHEN status = 'ASSIGNED' THEN
            '{"PENDING":0,"ASSIGNED":' || COALESCE(workload, 0) || ',"RECEIVED":0,"IN_PROGRESS":0,"SUBMITTED_FOR_QA":0,"QA_COMPLETING":0,"QA_COMPLETED":0}'
        WHEN status = 'RECEIVED' THEN
            '{"PENDING":0,"ASSIGNED":0,"RECEIVED":' || COALESCE(workload, 0) || ',"IN_PROGRESS":0,"SUBMITTED_FOR_QA":0,"QA_COMPLETING":0,"QA_COMPLETED":0}'
        WHEN status = 'IN_PROGRESS' THEN
            '{"PENDING":0,"ASSIGNED":0,"RECEIVED":0,"IN_PROGRESS":' || COALESCE(workload, 0) || ',"SUBMITTED_FOR_QA":0,"QA_COMPLETING":0,"QA_COMPLETED":0}'
        WHEN status = 'SUBMITTED_FOR_QA' THEN
            '{"PENDING":0,"ASSIGNED":0,"RECEIVED":0,"IN_PROGRESS":0,"SUBMITTED_FOR_QA":' || COALESCE(workload, 0) || ',"QA_COMPLETING":0,"QA_COMPLETED":0}'
        WHEN status = 'QA_COMPLETING' THEN
            '{"PENDING":0,"ASSIGNED":0,"RECEIVED":0,"IN_PROGRESS":0,"SUBMITTED_FOR_QA":0,"QA_COMPLETING":' || COALESCE(workload, 0) || ',"QA_COMPLETED":0}'
        WHEN status = 'QA_COMPLETED' THEN
            '{"PENDING":0,"ASSIGNED":0,"RECEIVED":0,"IN_PROGRESS":0,"SUBMITTED_FOR_QA":0,"QA_COMPLETING":0,"QA_COMPLETED":' || COALESCE(workload, 0) || '}'
        WHEN status = 'COMPLETED' THEN
            '{"PENDING":0,"ASSIGNED":0,"RECEIVED":0,"IN_PROGRESS":0,"SUBMITTED_FOR_QA":0,"QA_COMPLETING":0,"QA_COMPLETED":' || COALESCE(workload, 0) || '}'
        WHEN status = 'PAUSED' THEN
            '{"PENDING":0,"ASSIGNED":0,"RECEIVED":0,"IN_PROGRESS":' || COALESCE(workload, 0) || ',"SUBMITTED_FOR_QA":0,"QA_COMPLETING":0,"QA_COMPLETED":0}'
        WHEN status = 'FAILED' THEN
            '{"PENDING":0,"ASSIGNED":0,"RECEIVED":0,"IN_PROGRESS":' || COALESCE(workload, 0) || ',"SUBMITTED_FOR_QA":0,"QA_COMPLETING":0,"QA_COMPLETED":0}'
        ELSE
            '{"PENDING":' || COALESCE(workload, 0) || ',"ASSIGNED":0,"RECEIVED":0,"IN_PROGRESS":0,"SUBMITTED_FOR_QA":0,"QA_COMPLETING":0,"QA_COMPLETED":0}'
    END
)
WHERE category IN ('PROJECT', 'PHASE')
  AND status_workloads IS NULL
  AND workload IS NOT NULL
  AND workload > 0
  AND NOT EXISTS (
      SELECT 1 FROM tasks child WHERE child.parent_task_id = tasks.id
  );
